version: "3.9"
services:
  database:
    image: postgres:13.3
    volumes:
      - blog4j-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog4j
  app:
    image: blog4j
    build: .
    depends_on:
      - database
    expose:
      - "8080"
    volumes:
      - blog4j-web:/var/www/blog
    environment:
      - "BLOG4J_BLOG_HEADER=Example Blog"
      - "BLOG4J_BLOG_FOOTER=\u00a9 Example Blog"
      - "BLOG4J_BLOG_TITLE=Example Blog"
      - "BLOG4J_USERNAME=admin"
      - "BLOG4J_PASSWORD=admin"
      - TZ=Europe/Berlin
  web:
    image: nginx:1.21.1
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/blog:/etc/nginx/conf.d/default.conf
      - blog4j-web:/var/www/blog

volumes:
  blog4j-data:
  blog4j-web:
